### PR TITLE
Show successful failed test runs

### PR DESCRIPTION
**Pull request by Inventitech**

### CODE REVIEW

**Comment by Inventitech** [comment]
Btw.: If you understood why the tests failed in the first build executed on Travis, you're more than welcome to enlighten me.

**Comment by levaja** [comment]
First thing that comes to my mind is that some other event happens instead of the one expected, which is only due to concurrency (so, it won't happen every time). This is backed up by different failures in [Build #414](https://travis-ci.org/TestRoots/watchdog/builds/59565788) and [Build #416](https://travis-ci.org/TestRoots/watchdog/builds/59729978).

Another thing is that [this line](https://github.com/TestRoots/watchdog/blob/master/WatchDogEclipsePlugin/WatchDogUnitTests/src/nl/tudelft/watchdog/logic/interval/IntervalPersisterInvalidDatabaseTest.java#L23) causes tests in that file to fail when I execute them locally, because of the NullPointerException when creating a database with `copiedDatabase` File as a parameter. Not really sure if it is related to failed builds.

**Comment by Inventitech** [comment]
Your last paragraph bugs me a bit. The tests fail for you locally? That should not be the case.

**Comment by levaja** [comment]
Yes, they fail both in Eclipse and when they're executed from command line (with Maven). When the mentioned line is omitted, it's fine.

**Comment by Inventitech** [comment]
OK, could you try to solve the issue (preserving the "offending" line of course)?

**Comment by levaja** [comment]
I'll look into it now.

**Comment by levaja** [comment]
One simple way to solve this is to add PrintWriter as a private static field, and to move `writer.close()` to `@AfterClass` method. Would this solution be appropriate?

**Comment by levaja** [comment]
Ok, I went more into depth of this issue, with checking MapDB sources. Apparently, `IOException` is thrown with the following stack trace:

```
java.io.IOError: java.io.IOException: storage has invalid header
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:243)
	at org.mapdb.StoreWAL.checkHeaders(StoreWAL.java:115)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
	at org.mapdb.StoreWAL.<init>(StoreWAL.java:74)
	at org.mapdb.DBMaker.extendStoreWAL(DBMaker.java:928)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:722)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at nl.tudelft.watchdog.logic.interval.IntervalPersister.createDatabase(IntervalPersister.java:70)
	at nl.tudelft.watchdog.logic.interval.IntervalPersister.initalizeDatabase(IntervalPersister.java:58)
	at nl.tudelft.watchdog.logic.interval.IntervalPersister.recreateDatabase(IntervalPersister.java:78)
	at nl.tudelft.watchdog.logic.interval.IntervalPersister.<init>(IntervalPersister.java:41)
	at nl.tudelft.watchdog.logic.interval.IntervalPersisterInvalidDatabaseTest.setUpBeforeMethod(IntervalPersisterInvalidDatabaseTest.java:33)
```

We can see that the problem is in method checkHeaders of `StoreDirect` class which apparently (by its JavaDoc) "has zero protection from data corruption".

I'm looking into this further. (this whole comment is more for myself, just to keep track of my thoughts)

**Comment by levaja** [comment]
@Inventitech are these test failures from the first builds still relevant?

**Comment by Inventitech** [comment]
Nope.

**Comment by levaja** [comment]
Great. I'm off to IntelliJ now.

**Pull request merged**
