### PR TITLE
Improvements to the WDView

### PR DESCRIPTION
**Pull request by nspruit**
Fixes the issues described in #247 and #248 and adds the events that occur within 20s before the debugging session in the chart as well. The resulting WDViews:

**Eclipse:**
new wdview eclipse

**IntelliJ:**
new wdview ijtop
new wdview ijbottom

### CODE REVIEW

**Comment by Inventitech** [comment]
Hm, now the Eclipse view looks very distorted and has no more scroll bars?

**Comment by nspruit** [comment]
Nope, scroll bars are only added if the content does not entirely fit on the screen. If you have the WDView maximized with a full-HD resolution, all content 'fits', so there are no scroll bars.

**Comment by Inventitech** [comment]
Do you find the look of the Eclipse View acceptable? :-) Is there anything we can do? Specify a certain aspect ratio for the graphs?

**Comment by nspruit** [comment]
No :-) I've tried something like this before without success, but I'll see if there is anything we can do

**Comment by Inventitech** [comment]
Highly appreciated!

**Comment by nspruit** [comment]
It took me a few hours, but I've finally found a way to avoid the distorted view in Eclipse. I've also changed the order of the debug view and the debug statistics as it looks better IMO.

The new eclipse view:
eclipse1
eclipse2
eclipse3

**Comment by Inventitech** [comment]
3 line code change? :-)
Awesome.

**Comment by nspruit** [comment]
Yes, after changing a lot of lines, only three lines do the trick :)

**Pull request merged**
