### PR TITLE
Adds support for tracking a debug interval

### PR DESCRIPTION
**Pull request by nspruit**
This PR adds support for tracking ~~and visualizing~~ debug intervals. For this, the following steps have been performed:

1. Add DebugInterval type to the core project
2. Add a start and end debug event and adapt the EventManager to create/close DebugIntervals based on these events
3. Generate these debug events by adding a new listener for events fired by the debugger in both IJ and Eclipse
4. ~~Add a Debugging activity to the first two plots in the WatchDogView of both IDEs based on the 
generated DebugIntervals~~

~~The results of these steps can be seen in the following two screenshots showing the WatchDogView in both IDEs:~~

### CODE REVIEW

**Comment by Inventitech** [comment]
Cool. Just one question, and that might be because I don't know when a case DebugEvent.CREATE or TERMINATE event is thrown: Why do you represent debugging as opposed to reading and writing? Couldn't you be debugging and writing or reading?

**Comment by Inventitech** [comment]
I was meaning to release WD-1.7 with the new bug fixes; would you consider this to be stable enough to make it into the new release, or would you rather like to wait and release it with the rest of the debug functionality?

**Comment by nspruit** [comment]
From the documentation: 
* CREATE - a debug target has been created and is ready to begin a debug session.
* TERMINATE - a debug target has terminated and the debug session has ended.

So you're right, you can still read or write while debugging. Therefore, the development activities in the new WDView are no longer disjoint. However, the currently shown activities in the view can all overlap with a debug interval. So: do you have an idea where to show this new activity in the view?

Based on this finding I would postpone the integration of this PR to the next release. This will also be easier for analysing the data later on, as I can then filter out all WD versions except the one containing all functionality for tracking debug activities (v2.0?).

**Comment by Inventitech** [comment]
OK, sounds good to me.

**Comment by Inventitech** [comment]
What about displaying it in a new chart row on debugging? :)

**Comment by nspruit** [comment]
That is an appropriate solution, I'll see what might be interesting to visualize in this row in Phase 4.

For now, I'll remove the debugging statistics from the WDView.

**Comment by nspruit** [comment]
The changes to the WDView have now been reverted, so this PR now only makes sure that debug intervals are tracked.

**Comment by Inventitech** [comment]
Hi Niels,

Can you file this PR against the new branch wd-2.0? Then I can directly accept it .

Moritz

**Comment by nspruit** [comment]
Sure, see #235. I'll close this PR then

**Pull request closed without merging**
