### PR TITLE
Add more Eclipse and IntelliJ specific files to gitignore

### PR DESCRIPTION
**Pull request by TimvdLippe**
These files were cluttering the diff if another developers opens this project in their IDE. Since these files are automatically updated for local development and not required for building, they can be safely ignored.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
@Inventitech Rebased this PR on master as well :smile:

**Comment by Inventitech** [comment]
Hi Tim, 

I am a bit hesitant on this one. In particular, the fact that this also deletes the iml file, which is mentioned in step 4 of our "How we develop" guide:
"Import WatchDogIntelliJ as an IntelliJ module by selecting the IML file from its subfolder. We now have 1 module in our project." 

I am happy to merge this if you can show me that even with these changes, generating working plug-ins still goes OK (wiki: https://github.com/TestRoots/watchdog/wiki/How-we-develop).

**Comment by TimvdLippe** [comment]
**only now realizes there is actually a developer workflow described**

Yeah I am working on a different PR now that must include the `iml` files. Hopefully I can finish that one soon and publish it

**Comment by Inventitech** [comment]
OK if I close this?

**Comment by TimvdLippe** [comment]
Yup. Is superseded by my current work :)

Op wo 6 dec. 2017 om 17:04 schreef Moritz Beller <notifications@github.com>:

**Pull request closed without merging**
