### PR TITLE
Change registration process to make the survey link stand out more

### LINKED ISSUE #257: Remove In-IDE survey and make silent registrations to make Debug survey stand out

### PR DESCRIPTION
**Pull request by nspruit**
This should close #257 
The wizards (after a successful anonymous registration) now look as follows:

**IntelliJ:**
new wizard ij

**Eclipse:**
new wizard eclipse

I've left the dead code in the code base, as I think that might be easier once we want to revert the changes later on.

### CODE REVIEW

**Comment by Inventitech** [comment]
Thanks, looks good! Would it perhaps be better to say on page 1, that an anonymous registration will be performed (with all the other links) and on page 2, the debugging link is displayed. I hope that's not too much rework?
Could you also file this against a new branch branched off the dev branch? Reason is that we probably want to switch back to the old registration dialog some time.

**Comment by nspruit** [comment]
Sure, I'll see if I can do that.
I already wanted to do that, but I don't have push rights to the repo, so I can't create a new branch...

**Comment by Inventitech** [comment]
Ah ... Maybe it's time to give you these rights :-)
Am 12.05.2016 10:26 vorm. schrieb "Niels Spruit" <notifications@github.com>:

**Comment by nspruit** [comment]
Cool, then I'll close this PR for now and open a new one once I'm finished

**Pull request closed without merging**
