### PR TITLE
Removes duplication warnings

### PR DESCRIPTION
**Pull request by Inventitech**
@gousiosg, could you have a look at this small change?

Refs #174

### CODE REVIEW

**Comment by gousiosg** [comment]
This looks a bit strange (in my eyes at least): I would do the function passing by name using `send` like this.

```ruby
def f(a,b)  
  a + b 
end

def g(f, a, b)
  self.send(f, a, b)
end

g('f', 1, 2)
```

(Sorry, commented on the wrong PR.)

**Comment by gousiosg** [comment]
BTW, since you are into CI and quality tools, you might want to check out: https://scrutinizer-ci.com

**Comment by Inventitech** [comment]
How about that now?

I integrated Scrutinizer. It found two issues. Would you care to fix them? Thank you :-)

**Comment by gousiosg** [comment]
Done.

**Pull request merged**
