### PR TITLE
Get rid of multiple get interval definitions and consolidate to type-safe variant

### PR DESCRIPTION
**Pull request by Inventitech**

### CODE REVIEW

**Comment by levaja** [comment]
This branch doesn't have the new repo layout, I guess you didn't use the latest version of repo?

**Comment by Inventitech** [comment]
No prob.

**Comment by levaja** [comment]
Okay, as far as I can see from the commits, this should do the work - IntervalStatistics can now have its own methods for subtypes.

**Comment by levaja** [comment]
I think this folder has been left here unintentionally: 

https://github.com/TestRoots/watchdog/tree/master/WatchDog/src/nl/tudelft/watchdog/logic/interval/intervaltypes

If it should be removed, would you do it, or maybe I can add this change to #142 ?

**Pull request merged**
