### PR TITLE
Clarify installation of local IntelliJ SDK and CheckStyle jar

### PR DESCRIPTION
**Pull request by TimvdLippe**
This should clarify more how to get IntelliJ running locally. I have added the mention of the `fetchIdea.sh` script as well as explained more thoroughly how to install CheckStyle in your SDK.

### CODE REVIEW

**Comment by Inventitech** [comment]
IMHO, the " Install the Checkstyle Plugin via Settings > Plugins > Browse repositories ... and searching for "CheckStyle-IDEA". The plugin comes from https://infernus.org/ and https://github.com/jshiell/checkstyle-idea" bullet point (which I added) is not really necessary, or is it?

**Comment by TimvdLippe** [comment]
It is still necessary to test the CheckStyle integration of WatchDog. The IDE you run using the run configuration is a separate instance of the editor. Therefore, its plugins are separately installed as well. WatchDog itself has an optional dependency on CheckStyle, meaning that it can run without CheckStyle available. However, to test the integration, the CheckStyle plugin is required to be installed on the new instance.

**Comment by TimvdLippe** [comment]
@Inventitech Friendly ping 😄

**Comment by Inventitech** [comment]
Reopening this, as the IntelliJ uploader is not happy with the manual inclusion of the Checkstyle jar, since it also defines a plugin.xml.

**Pull request merged**
